package net.lebourreau.netheritevariants.item.custom;

import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.TooltipFlag;

import java.util.List;

public class BlazedStaffItem extends Item {
    public BlazedStaffItem(Properties properties) {
        super(properties);
    }

    @Override
    public void appendHoverText(ItemStack stack, TooltipContext context, List<Component> tooltipComponents, TooltipFlag tooltipFlag) {
        if (Screen.hasShiftDown()) {
            tooltipComponents.add(Component.translatable("tooltip.netheritevariants.blazed_netherite_staff.shift_down"));
        } else {
            tooltipComponents.add(Component.translatable("tooltip.netheritevariants.blazed_netherite_staff"));
        }

        super.appendHoverText(stack, context, tooltipComponents, tooltipFlag);
    }

    @Override
    public InteractionResult interactLivingEntity(
            ItemStack stack,
            Player player,
            LivingEntity interactionTarget,
            InteractionHand usedHand
    ) {

        // Don't work on players
        if (interactionTarget instanceof Player) {
            return InteractionResult.PASS;
        }

        // Don't work on bosses (EntityTypeTags.BOSSES doesn't exist)
        //if (interactionTarget.getType().is(EntityTypeTags.BOSSES)) {
        //    return InteractionResult.PASS;
        //}

        if (player.getCooldowns().isOnCooldown(this)) {
            return InteractionResult.FAIL;
        }

        if (!player.level().isClientSide()) {

            EntityType<?> type = interactionTarget.getType();

            // Get the spawn egg for this entity type
            SpawnEggItem egg = SpawnEggItem.byId(type);

            // Some entities do not have spawn eggs
            if (egg != null) {

                ItemStack eggStack = new ItemStack(egg);

                // Give egg to player
                if (!player.addItem(eggStack)) {
                    player.drop(eggStack, false);
                }

                player.level().playSound(null,
                        player.getX(), player.getY(), player.getZ(),
                        SoundEvents.ITEM_PICKUP, SoundSource.PLAYERS,
                        0.2f, 1.0f);
            }

            // Remove the entity
            interactionTarget.discard();

            // Damage the staff
            stack.hurtAndBreak(1, player,
                    LivingEntity.getSlotForHand(usedHand));
        }

        // For the future maybe try to make cooldown individual
        // (see resources/other/cooldown_code_example.txt for the template generated by chatgpt)
        // Add 10 second cooldown (200 ticks)
        if (!player.isCreative())
            player.getCooldowns().addCooldown(this, 200);

        return InteractionResult.SUCCESS;
    }
}
